#!/bin/sh
### BEGIN INIT INFO
# Provides:          xvfb
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts or stops the Xvfb daemon.
# Description:       Starts and stops Xvfb, virtual X11 server
### END INIT INFO

# clear environment
unset TMPDIR

NAME=xvfb
DAEMON=/usr/bin/Xvfb
CHUSER=xvfb
PIDFILE=/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME


test -x "$DAEMON" || exit 0
XVFBDISPLAY=":99.0"
XVFBARGS="$XVFBDISPLAY -screen 0 1024x768x24 -ac +extension GLX +render -noreset"
[ -r /etc/default/$NAME ] && . /etc/default/$NAME


. /lib/lsb/init-functions

case "$1" in
    start)
    status=`status_of_proc -p "$PIDFILE" "$DAEMON"`
        if [ $? -eq 0 ]; then
                log_daemon_msg "$NAME" "already running"
                log_end_msg 0
        else
                log_daemon_msg "Starting" "$NAME"
                start-stop-daemon --start --quiet --pidfile "$PIDFILE" --make-pidfile --background --chuid $CHUSER --exec $DAEMON -- $XVFBARGS
                log_end_msg $?
        fi
        ;;
    stop)
        status=`status_of_proc -p "$PIDFILE" "$DAEMON"`
        if [ $? -eq 0 ]; then
                log_daemon_msg "Stopping" "$NAME"
                start-stop-daemon --pidfile "$PIDFILE" --stop --retry=TERM/30/KILL/5 --quiet --oknodo --exec "$DAEMON"
                log_end_msg $?
        else
                log_daemon_msg "$NAME" "not running"
                log_end_msg 0
        fi
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON"
        exit $R
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
